sudo: required
services:
     - docker
before_install:
     # Tag your image with -t 
     - docker build -t ridaba/docker-react -f Dockerfile.dev .
script:
   -  docker run -e CI=true ridaba/docker-react yarn run test -- --coverage

deploy:
     edge: true
     provider: elasticbeanstalk
     # Copy and paste your region from Docker-react.eba-mhc7ft6t.eu-west-3.elasticbeanstalk.com
     region: "eu-west-3"
     app: "docker"
     env: "Docker-env-1"
     # Search your S3 created by Elastic Beanstalk
     bucket_name: "elasticbeanstalk-eu-west-3-733030400647"
     bucket_path: "docker"
     on:
          branch: master	
     # Env Variables Setup
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
       