sudo: required
services:
     - docker
before_install:
     # Tag your image with -t 
     - docker build -t ridaba/docker-react -f Dockerfile.dev .
script:
   -  docker run -e CI=true ridaba/docker-react npm run test -- --coverage

deploy:
     edge: true
     provider: elasticbeanstalk
     # Copy and paste your region from Docker-env.qbtbvwcxmh.us-west-2.elasticbeanstalk.com
     region: "eu-north-1"
     app: "docker-react"
     env: "DockerReact-env"
     # Search your S3 created by Elastic Beanstalk
     bucket_name: "elasticbeanstalk-eu-north-1-036706582541"
     bucket_path: "docker-react"
     on:
          branch: master	
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: 
          secure: $AWS_SECRET_KEY
       