version: '3'
services:
    web:  
        build: 
            context: .
            dockerfile:  Dockerfile
        ports:
            - "4000:3000"
        volumes:
            - /app/nodes_modules
            - .:/app/
        stdin_open: true

    tests:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /app/nodes_modules
            - .:/app/
        command: ["yarn", "run", "test"]
        stdin_open: true
        
