#Specify a base image
FROM node:16-alpine
#Specify working directory
WORKDIR '/app'
#Specify dependencies
COPY package*.json ./
RUN npm install
COPY . .
#Run default command
CMD ["npm","run","start"]

