sudo: required
services:
     - docker
before_install:
     # Tag your image with -t 
     - docker build -t ridaba/docker-react -f Dockerfile.dev .
script:
   -  docker run ridaba/docker-react npm run test -- --coverage